name: Build ReelForge.exe

on:
  workflow_dispatch:
  push:
    tags: ["v*"]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Publish Windows app
        run: dotnet publish ReelForge.sln -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -o publish
      - name: Package
        shell: pwsh
        run: Compress-Archive -Path publish\* -DestinationPath ReelForge-windows.zip
      - uses: actions/upload-artifact@v4
        with:
          name: ReelForge-windows
          path: ReelForge-windows.zip
      - name: Configure native C++ editor
        run: cmake -S Native/ReelForgeNative -B Native/ReelForgeNative/build -G "Visual Studio 17 2022" -A x64
      - name: Build native C++ editor
        run: cmake --build Native/ReelForgeNative/build --config Release
      - name: Package native C++ editor
        shell: pwsh
        run: Compress-Archive -Path Native\ReelForgeNative\build\Release\ReelForgeNative.exe -DestinationPath ReelForge-native-cpp-windows.zip
      - uses: actions/upload-artifact@v4
        with:
          name: ReelForge-native-cpp-windows
          path: ReelForge-native-cpp-windows.zip